### ISSUE TITLE
High-zoom Basemap change to OSM & Toggle Imagery Basemap Button

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#83]
Change to Imagery when reaching a certain zoom-in level
- [x] Add button to toggle basemap from default to imagery and back again
- [x] Basemap changes to Streets at high zoom
- [x] Imagery button only available at small zoom
- [x] streets transparent so you can see labels at same time as imagery

**Comment by jfarmer91** [comment]
https://developers.arcgis.com/javascript/jssamples/map_switch_layer_on_zoom.html 
This is the sample ArcGIS API for Javascript code that would make this work. Could also allow basemaps to change through radio buttons

**Comment by jfarmer91** [comment]
Think I like the map changing to osm (Think its better than "streets") at high-zoom so that you have roads automatically labeled in an aesthetic fashion when you zoom in. Otherwise we would need to add a roads feature layer to the map and deal with the labeling of that layer ourselves. We can have the "hybrid" basemap able to toggle on and off at any point so people can see imagery with basic labels if they choose to

**Comment by jfarmer91** [comment]
https://developers.arcgis.com/javascript/jssamples/widget_toggle.html
This widget provided sample code for toggling different basemaps

**Comment by jfarmer91** [comment]
Specific settings for basemap options punted to Issue #121

**Comment by jfarmer91** [comment]
Closed by Pull Request #119
