### ISSUE TITLE
Review report page 

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#87]
- [x] Did I capture all the fields?
- [x] Does the field order make sense?
- [x] Did I mix up any fields? (manual processes can be messy!)

Reviewed all of these and added comments below with action items. (~jf)

**Comment by TheMapSmith** [comment]
Pushing to b3

**Comment by jfarmer91** [comment]
- [ ] Figure out what to do with Surface Type 2 if 'null.'
- [ ] Include 'Paved' field in 'Safety Information' section instead of 'Crossing Information' section. This refers to whether the roadway is appropriate for pavement markings (a safety feature). A crossing could have an Asphalt surface material but the roadway could be unconsolidated and therefore not paved. (FRA suggests that pavement must extend at least 100 feet from the crossing along the roadway to be considered paved).
- [ ] Remove 'Signs or Signals' (redundant)
- [ ] Remove 'Dynamic Envelope' (we don't have any in vt)
- [ ] Remove 'Wayside Horn' (we don't have any in vt)
- [ ] Remove 'Special Gates' (we don't have any of the special full barrier gates and any crossing with full gate protection and medians will be identified with the 'Gate Configuration' and 'Channelization' fields)
- [x] Move 'Traffic Signal Control', 'Traffic Signal Nearby', 'Traffic Pre-Signals', 'Storage Distance', and 'Stop-line Distance' to their own subsection within 'Safety Information' section. (All of these are rare)
- [x] Order this section with 'Traffic Signal Nearby' first, 'Traffic Signal Control' next, 'Traffic Signal Pre-Signals' next, 'Storage Distance', and finally 'Stop-line Distance'

**Comment by jfarmer91** [comment]
Fields I have Added Post Inspections That Should Be Included (Just plan, and possibly build, out the layout to include spots for these fields):
- [ ] 'RDS_FUNCL' or Functional Classification
- [ ] 'RDS_AOTCLASS' or AOT Classification
- [ ] 'IntRd500' or Intersection Road Within 500' of Crossing
- [ ] 'IntRdDist' Distance to Intersection if 'IntRd500' = Yes
- [ ] 'PaveMarkCond' or Pavement Marking Condition
- [ ] 'Num_Tracks' or Number of Railroad Tracks

**Comment by TheMapSmith** [comment]
Per voice:
- [ ] Only leave in 'Traffic Signal Nearby' from the above list

**Comment by TheMapSmith** [comment]
Migrated all notes to #100
